name: DevSecOps Pipeline


on:
  push:
    branches:
      - main

jobs:
  security:
    uses: ./.github/workflows/security.yml
    secrets: inherit  
    # inherit means pass all envs from parents to child

  build_push:
    needs: security
    uses: ./.github/workflows/build-push.yml
    secrets: inherit

  deploy:
    needs: build_push
    uses: ./.github/workflows/deploy.yml
    secrets: inherit      