name: DevSecOps Pipeline
on:
  push:
    branches:
      - main

jobs:
  security:
    uses: ./.github/workflows/security.yml
    secrets: inherit

  build_push:
    needs: security
    uses: ./.github/workflows/push.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    needs: build_push
    uses: ./.github/workflows/deploy-ec2.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit
